FROM opensuse/tumbleweed

LABEL description="Opensuse container w/ verilator"
LABEL maintainer="graham@efficient.computer"

# Basic configuration
RUN zypper --non-interactive refresh && \
	zypper --non-interactive update && \
	zypper --non-interactive install git cmake 

# Verilator
RUN zypper --non-interactive install \
		autoconf gcc gcc-c++ flex bison ccache numactl \
		python3 perl perl-doc gperftools-devel
RUN git clone https://github.com/verilator/verilator && \
        cd verilator && git pull && git checkout stable && \
        autoconf && ./configure && make -j`nproc` && \
        make install && rm -rf /verilator

