FROM opensuse/tumbleweed

LABEL description="Opensuse container w/ compiler toolchain infrastructure"
LABEL maintainer="graham@efficient.computer"

# Basic configuration
RUN zypper --non-interactive refresh && \
	zypper --non-interactive update && \
	zypper --non-interactive install git cmake 

# Verilator
RUN zypper --non-interactive install \
		python3 gcc gcc-c++ zlib-devel

RUN git clone https://github.com/llvm/llvm-project.git
RUN cd llvm-project && cmake -S llvm -B build -G "Unix Makefiles" \
	-DLLVM_ENABLE_PROJECTS="mlir;clang" \
	-DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
RUN cd llvm-project && make -j16 -C build && make -j -C build install
RUN git clone --recursive https://github.com/llvm/Polygeist polygeist
RUN cd polygeist && mkdir build && cd build && \
	cmake -G "Unix Makefiles" ../llvm-project/llvm \
	-DLLVM_ENABLE_PROJECTS="clang;mlir" \
	-DLLVM_EXTERNAL_PROJECTS="polygeist" \
	-DLLVM_EXTERNAL_POLYGEIST_SOURCE_DIR=.. \
	-DLLVM_ENABLE_ASSERTIONS=ON \
	-DCMAKE_BUILD_TYPE=RelWithDebInfo
RUN cd polygeist && cmake --build build -j16